name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch
    paths:
      - 'src/Natedpalm.SharedKernel/**'
jobs:
  publish:
    name: build, pack & publish to artifactory
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.200

      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          VERSION_REGEX: <Version>(.*)<\/Version>
          PROJECT_FILE_PATH: src/Natedpalm.SharedKernel/Natedpalm.SharedKernel.csproj
          NUGET_KEY: ${{secrets.ARTIFACTORY_KEY}}
          NUGET_SOURCE: https://natedpalm.jfrog.io/artifactory/api/nuget/natedpalm-nuget
          TAG_COMMIT: true
          TAG_FORMAT: v*